version: '3'
services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=8080
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - vector-db

  vector-db:
    image: semitechnologies/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
    ports:
      - "8080:8080"
